/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReservationInformation.java
 *
 * Created on Jan 25, 2012, 9:51:38 AM
 */
/**
 *
 * @author anearcan
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import java.text.*;
        

public class ReservationInformation extends javax.swing.JFrame {
    private Employee employee;
    private MemberAccount member;
    private Reservation reservationInfo;
    private Item item;
    private ReservationControl rControl;
    private ResultSet rsReservation = null;
    private java.util.Date today;
    private PrinterInterface printer;
    /** Creates new form ReservationInformation */

    public ReservationInformation() {
        initComponents();
        printer = new PrinterInterface();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        today = new java.util.Date();
        System.out.println(dateFormat.format(today));
        
    }

    public ReservationInformation(Employee employee, MemberAccount member, Integer rID) {
        initComponents();
        this.employee = employee;
        this.member = member;
        reservationInfo = new Reservation(rID, today);
        memberFirstname.setText(member.getFirstName());
        memberLastname.setText(member.getLastName());
        memberEmail.setText(member.getEmail());
        phoneNumber.setText(Integer.toString(member.getPhone()));    
        String dbUrl = "jdbc:mysql://host111.hostmonster.com:3306/sourceit_VideoStore";
        String queryRes = "SELECT reservationID, itemNo, itemTitle, pickUpDate FROM reservations WHERE reservationID = "+ rID;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection (dbUrl, "sourceit_SYSC","sysc4907");
            PreparedStatement stmtRes = con.prepareStatement(queryRes);
            rsReservation = stmtRes.executeQuery();
            
            while (rsReservation.next()) {
                itemTitle.setText(rsReservation.getString("itemTitle"));
                pickUpDate.setText(rsReservation.getDate("pickUpDate").toString());
            } //end while
            con.close();
        } //end try

        catch(ClassNotFoundException e) {e.printStackTrace();}
        catch(SQLException e) {e.printStackTrace();}
    }

   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        query1 = java.beans.Beans.isDesignTime() ? null : ((javax.persistence.EntityManager)null).createQuery("");
        printReservation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        memberFirstname = new javax.swing.JLabel();
        memberLastname = new javax.swing.JLabel();
        memberEmail = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pickUpDate = new javax.swing.JLabel();
        itemTitle = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservation Information");

        printReservation.setText("Print");
        printReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReservationActionPerformed(evt);
            }
        });

        jLabel1.setText("Member First Name:");

        jLabel2.setText("Member Last Name:");

        jLabel3.setText("Email:");

        jLabel4.setText("Phone Number:");

        jLabel5.setText("Reserved Item Information");

        memberFirstname.setText("__________");

        memberLastname.setText("__________");

        memberEmail.setText("__________");

        phoneNumber.setText("__________");

        jLabel10.setText("Title:");

        jLabel12.setText("Pick up date:");

        pickUpDate.setText("yyyy/mm/dd");

        itemTitle.setText("______");

        cancelButton.setText("Cancel Reservation");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                        .addComponent(printReservation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(memberEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(memberLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(memberFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemTitle)
                            .addComponent(pickUpDate))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(memberLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(memberEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(memberFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemTitle))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pickUpDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printReservation)
                    .addComponent(cancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// TODO add your handling code here:
    rControl.cancelReservation(member, reservationInfo.getReservationId());
    if(employee.IsAdmin() == true){
            try {
                new AdminLoginSuccess(employee).setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ReservationInformation.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ReservationInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
    }else{
        new LoginSuccessful(employee).setVisible(true);
    }
    this.setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

private void printReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReservationActionPerformed
// TODO add your handling code here:
    printer.printReservationInfo(reservationInfo, member);
    if(employee.IsAdmin() == true){
            try {
                new AdminLoginSuccess(employee).setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ReservationInformation.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ReservationInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
    }else{
        new LoginSuccessful(employee).setVisible(true);
    }
    this.setVisible(false);

}//GEN-LAST:event_printReservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReservationInformation().setVisible(true);
            }
        });
;
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel itemTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel memberEmail;
    private javax.swing.JLabel memberFirstname;
    private javax.swing.JLabel memberLastname;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel pickUpDate;
    private javax.swing.JButton printReservation;
    private javax.persistence.Query query1;
    // End of variables declaration//GEN-END:variables
}
